// tailwind.config.js
import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#bf3003",
        "on-primary-fixed": "#001452",
        "on-secondary-fixed": "#001452",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        secondary: "#4459a8",
        "on-surface": "#191c1d",
        "on-tertiary-fixed": "#3c0800",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        surface: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed-variant": "#0038b6",
        "outline-variant": "#c3c5d9",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#0052ff",
        background: "#f8f9fa",
        "on-surface-variant": "#434656",
        "primary-fixed": "#dde1ff",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed": "#dde1ff",
        "inverse-surface": "#2e3132",
        "surface-container": "#edeeef",
        "tertiary-fixed": "#ffdbd2",
        outline: "#737688",
        "surface-container-high": "#e7e8e9",
        "on-primary-container": "#dfe3ff",
        primary: "#003ec7",
        "on-tertiary-container": "#ffddd5",
        "surface-container-lowest": "#ffffff",
        tertiary: "#952200",
        "primary-fixed-dim": "#b7c4ff",
        "secondary-container": "#95aafe",
        "surface-tint": "#004ced",
        "on-background": "#191c1d",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed-variant": "#2b418f",
        "on-tertiary-fixed-variant": "#891e00",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb4a1",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-container": "#253b89",
        "inverse-primary": "#b7c4ff",
        "secondary-fixed-dim": "#b7c4ff",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [forms],
};
